# Generated by Django 3.1.1 on 2020-09-14 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_do_ano', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=10)),
                ('quantidade', models.IntegerField()),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dolarizado', models.BooleanField()),
                ('mes_carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteira.mes')),
            ],
        ),
    ]
