# Generated by Django 3.1.1 on 2020-09-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_carteira', models.CharField(blank=True, choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março')], max_length=200, verbose_name='Mês')),
                ('papel', models.CharField(max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=10, max_digits=20)),
                ('cotacao_atual', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dolarizado', models.BooleanField()),
                ('lucro', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
            ],
        ),
    ]
