# Generated by Django 3.1.1 on 2020-09-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel_venda', models.CharField(max_length=10)),
                ('mes_carteira_venda', models.CharField(blank=True, choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho')], max_length=200, verbose_name='Mês')),
                ('quantidade_venda', models.DecimalField(decimal_places=10, max_digits=20)),
                ('cotacao_atual_venda', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('preco_medio_venda', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dolarizado_venda', models.BooleanField()),
                ('lucro_venda', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
            ],
        ),
    ]
