# Generated by Django 3.0.5 on 2020-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='quantidade',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
