# Generated by Django 3.1.1 on 2020-09-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='mes_carteira',
            field=models.CharField(blank=True, choices=[('Janeiro', '01'), ('Fevereiro', '02'), ('Março', '03')], max_length=200, verbose_name='Mês'),
        ),
        migrations.DeleteModel(
            name='Mes',
        ),
    ]
