# Generated by Django 3.1.1 on 2020-09-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_auto_20200914_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='mes_carteira',
            field=models.CharField(blank=True, choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março')], max_length=200, verbose_name='Mês'),
        ),
    ]
