# Generated by Django 3.0.5 on 2020-09-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_auto_20200915_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='cotacao_atual',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
