# Generated by Django 3.1.1 on 2020-09-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0003_auto_20200917_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='preco_medio_venda',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
