# Generated by Django 3.0.5 on 2020-09-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0003_carteira_cotacao_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='cotacao_atual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
